import {
  APPEARANCE_TAB_IDS,
  FEATURES_TAB_IDS,
  NAV_IDS,
  SITE_PACKS_TAB_IDS,
  SITE_SETTINGS_TAB_IDS,
  type SettingsSearchItem,
} from "~constants"

interface LocalizedLabelDefinition {
  key: string
  fallback: string
}

export const SETTING_SEARCH_PAGE_LABEL_DEFINITIONS: Record<string, LocalizedLabelDefinition> = {
  [NAV_IDS.GENERAL]: { key: "navGeneral", fallback: "General" },
  [NAV_IDS.FEATURES]: { key: "navFeatures", fallback: "Features" },
  [NAV_IDS.SITE_SETTINGS]: { key: "navSiteSettings", fallback: "Site Settings" },
  [NAV_IDS.SITE_PACKS]: { key: "navSitePacks", fallback: "Site Packs" },
  [NAV_IDS.GLOBAL_SEARCH]: { key: "navGlobalSearch", fallback: "Global Search" },
  [NAV_IDS.APPEARANCE]: { key: "navAppearance", fallback: "Appearance" },
  [NAV_IDS.SHORTCUTS]: { key: "navShortcuts", fallback: "Keyboard Shortcuts" },
  [NAV_IDS.BACKUP]: { key: "navBackup", fallback: "Data Management" },
  [NAV_IDS.PERMISSIONS]: { key: "navPermissions", fallback: "Permissions" },
  [NAV_IDS.ABOUT]: { key: "navAbout", fallback: "About" },
}

export const SETTING_SEARCH_SUB_TAB_LABEL_DEFINITIONS: Record<string, LocalizedLabelDefinition> = {
  panel: { key: "panelTab", fallback: "Panel" },
  tabOrder: { key: "tabOrderTab", fallback: "Tab Order" },
  shortcuts: { key: "shortcutsTab", fallback: "Quick Buttons" },
  toolsMenu: { key: "toolboxMenu", fallback: "Toolbox" },
  [SITE_PACKS_TAB_IDS.UPDATES]: { key: "sitePacksTabUpdates", fallback: "Updates" },
  [FEATURES_TAB_IDS.TAB_SETTINGS]: { key: "tabSettingsTab", fallback: "Tab Settings" },
  [FEATURES_TAB_IDS.REMINDER]: { key: "reminderTab", fallback: "Alerts" },
  [FEATURES_TAB_IDS.OUTLINE]: { key: "outlineSettingsTitle", fallback: "Outline" },
  [FEATURES_TAB_IDS.CONVERSATIONS]: {
    key: "conversationsSettingsTitle",
    fallback: "Conversations",
  },
  [FEATURES_TAB_IDS.PROMPTS]: { key: "promptSettingsTitle", fallback: "Prompts" },
  [FEATURES_TAB_IDS.READING_HISTORY]: {
    key: "readingHistorySettings",
    fallback: "Reading History",
  },
  [FEATURES_TAB_IDS.CONTENT]: { key: "contentProcessing", fallback: "Content" },
  [FEATURES_TAB_IDS.TOOLBOX]: { key: "toolboxMenu", fallback: "Toolbox" },
  [SITE_SETTINGS_TAB_IDS.LAYOUT]: { key: "layoutTab", fallback: "Layout" },
  [SITE_SETTINGS_TAB_IDS.MODEL_LOCK]: { key: "tabModelLock", fallback: "Model Lock" },
  gemini: { key: "geminiSettingsTab", fallback: "Gemini" },
  aistudio: { key: "aistudioSettingsTitle", fallback: "AI Studio" },
  chatgpt: { key: "chatgptSettingsTitle", fallback: "ChatGPT" },
  claude: { key: "claudeSettingsTab", fallback: "Claude" },
  [APPEARANCE_TAB_IDS.PRESETS]: { key: "themePresetsTab", fallback: "Theme Presets" },
  [APPEARANCE_TAB_IDS.CUSTOM]: { key: "customStylesTab", fallback: "Custom Styles" },
}

export const SETTING_SEARCH_TITLE_KEY_MAP: Record<string, string> = {
  "aistudio-collapse-advanced": "aistudioCollapseAdvanced",
  "aistudio-collapse-navbar": "aistudioCollapseNavbar",
  "aistudio-collapse-run-settings": "aistudioCollapseRunSettings",
  "aistudio-collapse-tools": "aistudioCollapseTools",
  "aistudio-enable-search": "aistudioEnableSearch",
  "aistudio-markdown-fix": "aistudioMarkdownFixLabel",
  "aistudio-remove-watermark": "aistudioRemoveWatermark",
  "appearance-custom-styles": "customCSS",
  "appearance-sync-native-page-theme": "syncNativePageThemeLabel",
  "appearance-preset-dark": "darkModePreset",
  "appearance-preset-light": "lightModePreset",
  "chatgpt-markdown-fix": "chatgptMarkdownFixLabel",
  "conversation-sync-delete": "conversationsSyncDeleteLabel",
  "global-search-fuzzy-search": "globalSearchEnableFuzzySearchLabel",
  "global-search-double-shift": "doubleShiftToSearch",
  "global-search-shortcut-setting-link": "globalSearchShortcutSettingLabel",
  "global-search-prompt-enter-behavior": "globalSearchPromptEnterBehaviorLabel",
  "claude-session-keys": "claudeSessionKeyTitle",
  "content-assistant-mermaid": "assistantMermaidLabel",
  "content-formula-copy": "formulaCopyLabel",
  "content-formula-copy-format": "formulaCopyFormatLabel",
  "content-formula-delimiter": "formulaDelimiterLabel",
  "content-table-copy": "tableCopyLabel",
  "content-user-query-markdown": "userQueryMarkdownLabel",
  "conversation-folder-rainbow": "folderRainbowLabel",
  "conversation-sync-unpin": "conversationsSyncUnpinLabel",
  "export-custom-model-name": "exportCustomModelName",
  "export-custom-user-name": "exportCustomUserName",
  "export-default-format": "exportDefaultFormatLabel",
  "export-filename-timestamp": "exportFilenameTimestamp",
  "export-include-thoughts": "exportIncludeThoughtsLabel",
  "export-packaging": "exportPackagingLabel",
  "gemini-markdown-fix": "markdownFixLabel",
  "gemini-policy-max-retries": "maxRetriesLabel",
  "gemini-policy-retry": "policyRetryLabel",
  "gemini-watermark-removal": "watermarkRemovalLabel",
  "layout-page-width-enabled": "enablePageWidth",
  "layout-page-width-value": "pageWidthValueLabel",
  "layout-panel-avoidance-enabled": "panelAvoidanceLabel",
  "layout-user-query-width-enabled": "enableUserQueryWidth",
  "layout-user-query-width-value": "userQueryWidthValueLabel",
  "layout-zen-mode-enabled": "zenModeTitle",
  "layout-zen-mode-exit-button-visible": "zenModeExitButtonVisibleLabel",
  "outline-auto-update": "outlineAutoUpdateLabel",
  "outline-follow-mode": "outlineFollowModeLabel",
  "outline-inline-bookmark-mode": "inlineBookmarkModeLabel",
  "outline-panel-bookmark-mode": "panelBookmarkModeLabel",
  "outline-prevent-auto-scroll": "preventAutoScrollLabel",
  "outline-show-word-count": "outlineShowWordCountLabel",
  "outline-update-interval": "outlineUpdateIntervalLabel",
  "panel-default-position": "defaultPositionLabel",
  "panel-edge-distance": "defaultEdgeDistanceLabel",
  "panel-edge-snap-threshold": "edgeSnapThresholdLabel",
  "panel-edge-trigger-mode": "edgeTriggerModeLabel",
  "panel-height": "panelHeightLabel",
  "panel-hover-width": "panelHoverWidthLabel",
  "panel-mode": "panelModeLabel",
  "panel-resize-on-hover": "panelResizeOnHoverLabel",
  "panel-width": "panelWidthLabel",
  "prompt-double-click-send": "promptDoubleClickSendLabel",
  "prompt-queue": "queueSettingLabel",
  "prompt-quick-quote-enabled": "quickQuoteEnabledLabel",
  "quick-buttons-hide-when-panel-open": "quickButtonsHideWhenPanelOpenLabel",
  "quick-buttons-opacity": "quickButtonsOpacityLabel",
  "quick-buttons-proximity-radius": "quickButtonsProximityRadiusLabel",
  "reading-history-auto-restore": "readingHistoryAutoRestoreLabel",
  "reading-history-cleanup-days": "readingHistoryCleanup",
  "reading-history-persistence": "readingHistoryPersistenceLabel",
  "remote-config-active-patches": "remoteConfigActivePatchesLabel",
  "remote-config-auto-update": "remoteConfigAutoUpdateLabel",
  "remote-config-check-now": "remoteConfigCheckNowLabel",
  "site-pack-custom-origin": "sitePacksCustomOriginsTitle",
  "site-packs-registry": "sitePacksRegistryTitle",
  "shortcuts-enabled": "enableShortcuts",
  "shortcuts-global-url": "globalShortcutUrl",
  "shortcuts-browser-shortcuts": "globalShortcutsTitle",
  "shortcuts-prompt-submit-shortcut": "promptSubmitShortcutLabel",
  "tab-auto-focus": "autoFocusLabel",
  "tab-auto-rename": "autoRenameTabLabel",
  "tab-notification-sound": "notificationSoundLabel",
  "tab-notification-sound-preset": "notificationSoundPresetLabel",
  "tab-notification-volume": "notificationVolumeLabel",
  "tab-notification-repeat-count": "notificationRepeatCountLabel",
  "tab-notification-repeat-interval": "notificationRepeatIntervalLabel",
  "tab-notify-when-focused": "notifyWhenFocusedLabel",
  "tab-open-new": "openNewTabLabel",
  "tab-privacy-mode": "privacyModeLabel",
  "tab-privacy-title": "privacyTitleLabel",
  "tab-rename-interval": "renameIntervalLabel",
  "tab-show-notification": "showNotificationLabel",
  "tab-show-status": "showStatusLabel",
  "tab-hide-status-when-read": "hideStatusWhenReadLabel",
  "tab-title-format": "titleFormatLabel",
  "tools-menu-export": "export",
  "tools-menu-exportHTML": "exportToHTMLMenu",
  "tools-menu-copyMarkdown": "exportToClipboard",
  "tools-menu-move": "conversationsMoveTo",
  "tools-menu-setTag": "conversationsSetTag",
  "tools-menu-scrollLock": "shortcutToggleScrollLock",
  "tools-menu-modelLock": "modelLockTitle",
  "tools-menu-cleanup": "cleanup",
  "tools-menu-settings": "tabSettings",
  "usage-monitor-enabled": "usageMonitorEnabledLabel",
  "usage-monitor-daily-limit": "usageMonitorDailyLimitLabel",
  "usage-monitor-auto-reset": "usageMonitorAutoResetLabel",
}

export const MODEL_LOCK_SITE_LABEL_DEFINITIONS: Record<string, LocalizedLabelDefinition> = {
  gemini: { key: "globalSearchSiteGemini", fallback: "Gemini" },
  "gemini-enterprise": {
    key: "globalSearchSiteGeminiEnterprise",
    fallback: "Gemini Enterprise",
  },
  aistudio: { key: "globalSearchSiteAIStudio", fallback: "AI Studio" },
  chatgpt: { key: "globalSearchSiteChatGPT", fallback: "ChatGPT" },
  claude: { key: "globalSearchSiteClaude", fallback: "Claude" },
  grok: { key: "globalSearchSiteGrok", fallback: "Grok" },
  qwenai: { key: "globalSearchSiteQwenAi", fallback: "Qwen Studio" },
  ima: { key: "globalSearchSiteIma", fallback: "ima" },
  zai: { key: "globalSearchSiteZai", fallback: "Z.ai" },
}

export const MODEL_LOCK_SETTINGS_SEARCH_ITEMS: SettingsSearchItem[] = [
  {
    settingId: "model-lock-gemini",
    title: "模型锁定：Gemini",
    keywords: ["model lock", "gemini", "模型锁定"],
  },
  {
    settingId: "model-lock-gemini-enterprise",
    title: "模型锁定：Gemini Enterprise",
    keywords: ["model lock", "gemini enterprise", "模型锁定"],
  },
  {
    settingId: "model-lock-aistudio",
    title: "模型锁定：AI Studio",
    keywords: ["model lock", "aistudio", "模型锁定"],
  },
  {
    settingId: "model-lock-chatgpt",
    title: "模型锁定：ChatGPT",
    keywords: ["model lock", "chatgpt", "模型锁定"],
  },
  {
    settingId: "model-lock-claude",
    title: "模型锁定：Claude",
    keywords: ["model lock", "claude", "模型锁定"],
  },
  {
    settingId: "model-lock-grok",
    title: "模型锁定：Grok",
    keywords: ["model lock", "grok", "模型锁定"],
  },
  {
    settingId: "model-lock-kimi",
    title: "模型锁定：Kimi",
    keywords: ["model lock", "kimi", "模型锁定"],
  },
  {
    settingId: "model-lock-qianwen",
    title: "模型锁定：Qianwen",
    keywords: ["model lock", "qianwen", "tongyi", "通义千问", "模型锁定"],
  },
  {
    settingId: "model-lock-qwenai",
    title: "模型锁定：Qwen Studio",
    keywords: ["model lock", "qwen studio", "qwenai", "chat.qwen.ai", "国际版千问", "模型锁定"],
  },
  {
    settingId: "model-lock-yuanbao",
    title: "模型锁定：Yuanbao",
    keywords: ["model lock", "yuanbao", "腾讯元宝", "模型锁定"],
  },
  {
    settingId: "model-lock-ima",
    title: "模型锁定：ima",
    keywords: ["model lock", "ima", "ima.qq.com", "腾讯 ima", "模型锁定"],
  },
  {
    settingId: "model-lock-zai",
    title: "模型锁定：Z.ai",
    keywords: ["model lock", "z.ai", "zai", "模型锁定"],
  },
]

export const toSearchTitleFallback = (settingId: string): string =>
  settingId
    .replace(/[-_]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/\b([a-z])/g, (_matched, first) => first.toUpperCase())
