import { SITE_IDS, isBuiltinSiteId, type BuiltinSiteId } from "~constants/defaults"

export const SITE_PACK_CAPABILITIES = [
  "outline",
  "outline-user-queries",
  "document-outline",
  "conversation-list",
  "export-basic",
  "model-lock",
  "generation-detect",
  "new-chat",
  "stop-generation",
  "width",
  "panel-avoidance",
  "zen",
  "clean",
  "prompt-insert",
  "reading-history",
] as const

export type SitePackCapability = (typeof SITE_PACK_CAPABILITIES)[number]

export function getFeatureCapabilitiesSignature(
  capabilities: Iterable<SitePackCapability>,
): string {
  return Array.from(capabilities).sort().join("\u0000")
}

export function createFeatureCapabilitiesFromSignature(signature: string): Set<SitePackCapability> {
  return new Set(signature ? (signature.split("\u0000") as SitePackCapability[]) : [])
}

/**
 * 内置适配器的真实功能能力表。
 *
 * 每个站点必须显式列出能力，不能从“全能力”默认值派生，避免新增能力时被静默开放。
 */
export const BUILTIN_FEATURE_CAPABILITIES = {
  [SITE_IDS.AISTUDIO]: [
    "outline",
    "outline-user-queries",
    "conversation-list",
    "export-basic",
    "model-lock",
    "generation-detect",
    "new-chat",
    "stop-generation",
    "width",
    "zen",
    "clean",
    "prompt-insert",
    "reading-history",
  ],
  [SITE_IDS.CHATGLM]: [
    "outline",
    "outline-user-queries",
    "export-basic",
    "model-lock",
    "generation-detect",
    "new-chat",
    "stop-generation",
    "width",
    "zen",
    "clean",
    "prompt-insert",
    "reading-history",
  ],
  [SITE_IDS.CHATGPT]: [
    "outline",
    "outline-user-queries",
    "conversation-list",
    "export-basic",
    "model-lock",
    "generation-detect",
    "new-chat",
    "stop-generation",
    "width",
    "zen",
    "clean",
    "prompt-insert",
    "reading-history",
  ],
  [SITE_IDS.CLAUDE]: [
    "outline",
    "outline-user-queries",
    "document-outline",
    "conversation-list",
    "export-basic",
    "model-lock",
    "generation-detect",
    "new-chat",
    "stop-generation",
    "width",
    "zen",
    "clean",
    "prompt-insert",
    "reading-history",
  ],
  [SITE_IDS.DEEPSEEK]: [
    "outline",
    "outline-user-queries",
    "conversation-list",
    "export-basic",
    "generation-detect",
    "new-chat",
    "stop-generation",
    "width",
    "zen",
    "clean",
    "prompt-insert",
    "reading-history",
  ],
  [SITE_IDS.DOUBAO]: [
    "outline",
    "outline-user-queries",
    "conversation-list",
    "export-basic",
    "model-lock",
    "generation-detect",
    "new-chat",
    "stop-generation",
    "width",
    "zen",
    "clean",
    "prompt-insert",
    "reading-history",
  ],
  [SITE_IDS.GEMINI]: [
    "outline",
    "outline-user-queries",
    "document-outline",
    "conversation-list",
    "export-basic",
    "model-lock",
    "generation-detect",
    "new-chat",
    "stop-generation",
    "width",
    "zen",
    "clean",
    "prompt-insert",
    "reading-history",
  ],
  [SITE_IDS.GEMINI_ENTERPRISE]: [
    "outline",
    "outline-user-queries",
    "document-outline",
    "conversation-list",
    "export-basic",
    "model-lock",
    "generation-detect",
    "new-chat",
    "stop-generation",
    "width",
    "zen",
    "clean",
    "prompt-insert",
    "reading-history",
  ],
  [SITE_IDS.GROK]: [
    "outline",
    "outline-user-queries",
    "conversation-list",
    "export-basic",
    "model-lock",
    "generation-detect",
    "new-chat",
    "stop-generation",
    "width",
    "zen",
    "prompt-insert",
    "reading-history",
  ],
  [SITE_IDS.IMA]: [
    "outline",
    "outline-user-queries",
    "export-basic",
    "model-lock",
    "generation-detect",
    "new-chat",
    "stop-generation",
    "width",
    "zen",
    "clean",
    "prompt-insert",
    "reading-history",
  ],
  [SITE_IDS.KIMI]: [
    "outline",
    "outline-user-queries",
    "conversation-list",
    "export-basic",
    "model-lock",
    "generation-detect",
    "new-chat",
    "stop-generation",
    "width",
    "zen",
    "clean",
    "prompt-insert",
    "reading-history",
  ],
  [SITE_IDS.QIANWEN]: [
    "outline",
    "outline-user-queries",
    "export-basic",
    "model-lock",
    "generation-detect",
    "new-chat",
    "stop-generation",
    "width",
    "zen",
    "clean",
    "prompt-insert",
    "reading-history",
  ],
  [SITE_IDS.QWENAI]: [
    "outline",
    "outline-user-queries",
    "export-basic",
    "model-lock",
    "generation-detect",
    "new-chat",
    "stop-generation",
    "width",
    "zen",
    "clean",
    "prompt-insert",
    "reading-history",
  ],
  [SITE_IDS.YUANBAO]: [
    "outline",
    "outline-user-queries",
    "conversation-list",
    "export-basic",
    "model-lock",
    "generation-detect",
    "new-chat",
    "stop-generation",
    "width",
    "zen",
    "clean",
    "prompt-insert",
    "reading-history",
  ],
  [SITE_IDS.ZAI]: [
    "outline",
    "outline-user-queries",
    "export-basic",
    "model-lock",
    "generation-detect",
    "new-chat",
    "stop-generation",
    "width",
    "zen",
    "prompt-insert",
    "reading-history",
  ],
} as const satisfies Record<BuiltinSiteId, readonly SitePackCapability[]>

export function getBuiltinFeatureCapabilities(siteId: string): Set<SitePackCapability> {
  if (!isBuiltinSiteId(siteId)) return new Set()
  return new Set(BUILTIN_FEATURE_CAPABILITIES[siteId])
}
